# 环境配置文件选择
spring:
  profiles:
    active: test
server:
  port: 12581
  servlet:
    context-path: /luk
#配置mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  ##日志打印
logging:
  config: classpath:logback-spring.xml
